### ISSUE TITLE
Error "Sendbird Connection failed", after changing the appID in sample basic-javascript sample

### ISSUE THREAD

**Issue by rahulgupta999** [sendbird/SendBird-JavaScript#102]
![image](https://user-images.githubusercontent.com/4464201/67480560-cf410300-f67d-11e9-9875-78c1698f5d9d.png)

This happens on clicking login button. I can see that user is created on dashboard, however it still gives this error.

**Comment by fshiori** [comment]
same issue.

**Comment by rahulgupta999** [comment]
I think we need to add 'API token'' however unable to find that,

**Comment by ravi-intiva** [comment]
same issue

**Comment by AlexPrestonSB** [comment]
Hey @rahulgupta999 let me check into this, and see if I can reproduce this. As far as your API token you can find that on your dashboard.

**Comment by AlexPrestonSB** [comment]
Hey @rahulgupta999, just wanted to give you an update, I was able to reproduce the issue. I'll let you know when it is fixed.

**Comment by stevengpwc** [comment]
Same issue. Any way for a quick fix? Or checking out any previous version would help?

**Comment by AlexPrestonSB** [comment]
Hey @stevengpwc you should be able to use previous versions without any issues.

**Comment by kennethbrent** [comment]
Any update on this? Same issue here and this is what is being logged to my console.....I also don't see

```
main.js?cdd5:112 TypeError: L.get(...).GroupChannelListQuery is not a constructor
    at new value (SendBird.min.js?e6dc:3571)
    at SendBirdAction.getGroupChannelList (SendBirdAction.js?873d:290)
    at ChatLeftMenu.getGroupChannelList (ChatLeftMenu.js?b234:200)
    at eval (main.js?cdd5:110)
```

**Comment by khanm-ibl** [comment]
I got same issue

**Comment by RRAVITEJA** [comment]
"TypeError: Cannot add property url, object is not extensible" when using sb.connect()

**Comment by aibek-bird** [comment]
Should be resolved with recent sendbird package version update -> 3.0.111
