### ISSUE TITLE
ReactNative sendFileMessage Error 400105

### ISSUE THREAD

**Issue by bsehovac** [sendbird/SendBird-JavaScript#106]
I am getting `SendBirdException 400105 "file" must be required.` when trying to send file message, anyone else figured out how to solve this?

I am on `react-native@0.61.5` and `sendbird@^3.0.113`.

This is my code:

```javascript
ImagePicker.showImagePicker({ mediaType: 'photo', noData: true }, response => {
    if (response.didCancel || response.error) return
    const { uri, fileName, fileSize: size, type } = response
    const name = (fileName ? fileName : uri.split('/').pop()).toLowerCase()
    const file = { uri, name, type }
    const interval = setInterval(() => {
      Image.getSize(uri, () => {
        clearInterval(interval)
        sendFileMessage(file)
      })
    }, 100)
})
```

```javascript
sendFileMessage(file) {
  this.channel.sendFileMessage(file, (message, error) => {
    if (error) return resolve({ ok: false, error })
    resolve({ ok: true, message })
  })
}
```

File Object Passed

```javascript
{
  uri: "file:///Users/.boris/../C413034B-0783-4E5B-AFAB-17E278DA1C2D.jpg",
  name: "img_0007.jpg",
  type: "image/jpeg",
  size: 49900,
}
```

**Comment by AlexPrestonSB** [comment]
Hey @bsehovac, 

I think this may have to do with how you are passing the file. Are you just passing the file like you showed above?

**Comment by bsehovac** [comment]
Well yes, basically this:

’’’
channel.sendFileMessage({
  uri: "file:///Users/.boris/../C413034B-0783-4E5B-AFAB-17E278DA1C2D.jpg",
  name: "img_0007.jpg",
  type: "image/jpeg",
  size: 49900,
} , (message, error) => {})
’’’

Isn't this what is showed in examples or I'm missing something...

**Comment by AlexPrestonSB** [comment]
Hey @bsehovac, 

I actually just looked at internal tickets, and it looks like this issue was already reported and a fix is on its way. I will notify you once it is released.

**Comment by AlexPrestonSB** [comment]
Hey @bsehovac this fix has been released in the most recent release. 3.0.114.
