### ISSUE TITLE
How to get widget.SendBird.js file in my react app.

### ISSUE THREAD

**Issue by yaakuza** [sendbird/SendBird-JavaScript#107]
In implementing web-widget example in react I am facing a problem . How can I get  widget.SendBird.js in my react app. If I just copy the file then I'm getting a compilation error, in react

**Comment by janna-sendbird** [comment]
Hello @yaakuza . The web-widget sample was built with Vanilla JS and wasn't designed for React. That said, you may be able to wrap it into a React component for usage.
