### ISSUE TITLE
Group Channels with Admin messages not getting listed in channelListQuery 

### ISSUE THREAD

**Issue by midhunadarvin** [sendbird/SendBird-JavaScript#111]
Hi,
I have configured in sendbird dashboard to send an admin message while creating a private group channel.  Then i am trying to get the list of group channels ordered by the `latest_last_message`, but the newly created group channel is not coming first in the list. While analysing it is observed that the `lastMessage` property of the group channel is coming as `null`.

We are using sendbird javascript sdk version 3.0.117.

**Comment by AstinCHOI** [comment]
Moved to the zendesk ticket
