### ISSUE TITLE
What does error code of "0" mean?

### ISSUE THREAD

**Issue by flarnie-chegg** [sendbird/SendBird-JavaScript#98]
We are sometimes getting an error with the code of "0" and no message. The data logged looks like this:
```
{ code: 0, message: null, name: "SendBirdException" }
```
There is nothing in [the documentation](https://docs.sendbird.com/javascript/error_codes) about this error code.

This happens when we are calling `GroupChannel.getChannel`, in the callback we are getting the `error` argument with the code of "0".

Can you advise us on what this error code means?

Thanks so much~! :)

**Comment by janna-sendbird** [comment]
Hello @flarnie-chegg, the 0 code is a default error code from the JavaScript SDK. 
The method should be called from the SendBird instance after initialization and the current user is connected.

        this.sb.GroupChannel.getChannel(channelUrl, (groupChannel, error) => {
          error ? reject(error) : resolve(groupChannel);
        });

We'd be happy to take a closer look and help you debug this issue! File a support ticket with us by going to your application at dashboard.sendbird.com and going to the 'Support' section.

**Comment by flarnie-chegg** [comment]
Thanks @janna-sendbird !

I opened a support ticket, will close this.
