### ISSUE TITLE
"Web widget" file upload/share fails with error

### ISSUE THREAD

**Issue by ccshannon** [sendbird/SendBird-JavaScript#99]
Hi, I'm building a web-based chat widget using the "web-widget" app as the seed. When attempting to share/upload a file using the paperclip button, the file selector pops up, I select a jpeg file of 77KB, the popup disappears and ... that's it. Nothing else happens, no upload, no thumbnail, nothing. I checked the Console and see this error emanating from src/js/sendbird.js in the 'sendFileMessage' function ...

`name: "SendBirdException", code: 800110, message: "Invalid parameter."}
code: 800110
message: "Invalid parameter."
name: "SendBirdException` 

I've tried different parameters for the function in sendbird.js, as I think you've changed the sendFileMessage function in SendBird API but not this particular app's use of it. The web-basic-sample, for instance, does not have this issue.

Please let me know if I can provide further information. Thanks.

**Comment by AlexPrestonSB** [comment]
Hey @ccshannon, 

Can you provide the snippet of code you are using?

**Comment by ccshannon** [comment]
Hi, Alex.

I'm not sure what you mean by snippet of code -- it's not my code. It's the web-widget app inside this repo. Without making any changes to it, I npm install it, then I run 'npm run start:dev' and go to localhost:9000 in my browser. The paperclip button in the chat message window doesn't upload files. The console error is in the file 'src/js'sendbird.js' on line 151 --  see the following where it says console.log(error):

`  sendFileMessage(channel, file, action) {
    let thumbSize = [{
      maxWidth: 160,
      maxHeight: 160
    }];
    channel.sendFileMessage(file, '', '', thumbSize, (message, error) => {
      if (error) {
        console.error(error);
        return;
      }
      action(message);
    });
  }
`

Let me know if that helps. Thanks.

**Comment by AlexPrestonSB** [comment]
Hey @ccshannon we looked into it, this is a bug. Thank you for filing an issue. I'll let you know when it is fixed.

**Comment by ccshannon** [comment]
Thank you so much, Alex, for getting back to me so quickly and confirming. I look forward to the fix. The widget is otherwise working great. :)

**Comment by AlexPrestonSB** [comment]
Awesome to hear! I'll keep you posted.

**Comment by ccshannon** [comment]
Hi there, @AlexPrestonSB. Any updates on this? Just checking in. Let me know if I can assist in any way. Many thanks!

**Comment by AlexPrestonSB** [comment]
Hey @ccshannon I will check in with the Javascript team on this and see. Unfortunately they have been really busy as of late, so getting to this has simply been a matter of priority.

**Comment by AlexPrestonSB** [comment]
Hey @ccshannon we have update the web-widget-sample, you can run it locally using this repo
https://github.com/sendbird/SendBird-JavaScript/tree/master/web-widget

**Comment by ccshannon** [comment]
@AlexPrestonSB So sorry I never commented. I got swept up in a bunch of other tasks. I can't believe this was back in November! This works great, now, for me. Thanks so much!!!

**Comment by AlexPrestonSB** [comment]
No worries! Glad to hear!
